[project]
name = "nifty-500-live-sentiment-analysis"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "streamlit>=1.44.1",
]
