name: Copy sentiment_data.csv to streamlit branch

on: 
  workflow_run:
    workflows: ["Get Sentiment and update GitHub page"]
    types:
      - completed
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  copy-csv:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: streamlit
      
      - name: copy
        shell: bash
        run: |
          git checkout main -- ./datasets/ticker_data.db
          
      - name: commit files
        shell: bash
        run: |
          git config user.name "Deploy from CI"
          git config user.email ""
          git add .
          git commit -m "Deploy $GITHUB_SHA to streamlit"
          git push
