name: Manual Sentiment Analysis Test

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  run-sentiment-test:
    runs-on: ubuntu-latest
    env:
        python_version: "3.13"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install latest uv version
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.12"
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
        python-version: ${{ env.python_version }}`

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Run sentiment analysis test script
      run: uv run ./src/sentiment_analysis_test.py